# Generated by Django 5.2.8 on 2025-11-12 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amparado', '0001_initial'),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amparado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amparado_responsavel', to='amparado.amparado')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_responsavel', to='perfil.perfil')),
            ],
        ),
    ]
