# Generated by Django 5.2.8 on 2025-11-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_alter_responsavel_amparado'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='apelido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
