# Generated by Django 5.2.8 on 2025-11-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amparado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_convite', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
    ]
