# Generated by Django 5.2.8 on 2025-11-12 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amparado', '0001_initial'),
        ('autenticacao', '0002_alter_usuario_user'),
        ('perfil', '0002_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='amparado',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_amparado', to='perfil.responsavel'),
        ),
        migrations.AddField(
            model_name='amparado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amparado_usuario', to='autenticacao.usuario'),
        ),
    ]
