# Generated by Django 5.2.8 on 2025-11-15 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amparado', '0002_initial'),
        ('perfil', '0002_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amparado',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_amparado', to='perfil.responsavel'),
        ),
    ]
