# Generated by Django 5.2.8 on 2025-12-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amparado', '0003_alter_amparado_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amparado',
            name='codigo_convite',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
