# Generated by Django 5.2.8 on 2025-11-29 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0004_endereco_cep_perfil_apelido'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaSegura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('raio', models.FloatField()),
                ('nome', models.CharField(default='Área Segura', max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('responsavel_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.responsavel')),
            ],
        ),
    ]
