# Generated by Django 5.2.8 on 2025-11-30 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amparado', '0003_alter_amparado_responsavel'),
        ('localizacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Marcador', max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('amparado_markers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amparado.amparado')),
            ],
        ),
    ]
