# Generated by Django 5.2.8 on 2025-11-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_alter_usuario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_amparado',
            field=models.BooleanField(default=False),
        ),
    ]
