# Generated by Django 5.2.8 on 2025-11-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_usuario_is_amparado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('usuario', 'Usuário'), ('moderador', 'Moderador')], default='usuario', max_length=20, null=True),
        ),
    ]
