# Generated by Django 5.2.8 on 2025-11-19 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacao', '0004_alter_usuario_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='autenticacao.usuario')),
            ],
        ),
    ]
